### ISSUE TITLE
KeyError: 'results'

### ISSUE THREAD

**Issue by H4ckForJob** [wudicainiao/Fofa-Cscan#2]
环境：ubuntu x64、python3

已填写config.py配置

运行`python3 fofa-Cscan.py -i ****/24`报错：

```
[*]开始抓取
[*]创建文件成功 out/***.xlsx
Traceback (most recent call last):
  File "fofa-Cscan.py", line 73, in <module>
    [ip(s) for s in ipaddress.ip_network(str(sys.argv[2]),False)]
  File "fofa-Cscan.py", line 73, in <listcomp>
    [ip(s) for s in ipaddress.ip_network(str(sys.argv[2]),False)]
  File "fofa-Cscan.py", line 25, in ip
    [write_xlsx(i) for i in json.loads(res)["results"]]
KeyError: 'results'
```

**Comment by wudicainiao** [comment]
可能为输入的IP格式不正确导致，建议检查一下ip文件

**Comment by kay6666** [comment]
> 可能为输入的IP格式不正确导致，建议检查一下IP文件

我也遇到了同样的问题，您指的ip文件是什么，还是-i 后面的参数？

**Comment by wudicainiao** [comment]
有可能是ip的cidr格式没有输入正确。建议您检查下。


------------------ 原始邮件 ------------------
发件人: "kay6666"<notifications@github.com>;
发送时间: 2019年7月16日(星期二) 下午5:04
收件人: "wudicainiao/Fofa-Cscan"<Fofa-Cscan@noreply.github.com>;
抄送: "dacainiao"<820340571@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [wudicainiao/Fofa-Cscan] KeyError: 'results' (#2)



 
可能为输入的IP格式不正确导致，建议检查一下IP文件
  
我也遇到了同样的问题，您指的ip文件是什么，还是-i 后面的参数？

**Comment by H4ckForJob** [comment]
> > 可能为输入的IP格式不正确导致，建议检查一下IP文件
> 
> 我也遇到了同样的问题，您指的ip文件是什么，还是-i 后面的参数？

我的-i 参数是`*.*.*.*/24`

`*.*.*.*`是目标ip

**Comment by wudicainiao** [comment]
能截图全部报错信息吗
  

 

 ------------------ 原始邮件 ------------------
  发件人: "I Need A job!"<notifications@github.com>;
 发送时间: 2019年7月17日(星期三) 中午1:49
 收件人: "wudicainiao/Fofa-Cscan"<Fofa-Cscan@noreply.github.com>;
 抄送: "dacainiao"<820340571@qq.com>;"Comment"<comment@noreply.github.com>;
 主题: Re: [wudicainiao/Fofa-Cscan] KeyError: 'results' (#2)

 

   
可能为输入的IP格式不正确导致，建议检查一下IP文件
 
我也遇到了同样的问题，您指的ip文件是什么，还是-i 后面的参数？
 
我的-i 参数是*.*.*.*/24
 
*.*.*.*是目标ip

**Comment by lgf01010** [comment]
![image](https://user-images.githubusercontent.com/41816999/62685986-5b844800-b9f6-11e9-8ad1-de703aeb7b56.png)
这个错是为啥，然后这个老歌results也报

**Comment by 98Kstar** [comment]
![image](https://user-images.githubusercontent.com/41816999/62686330-1d3b5880-b9f7-11e9-8e08-bfb43d345c19.png)
[*]开始抓取
Traceback (most recent call last):
  File "fofa-Cscan.py", line 73, in <module>
    creat_xlsx()
  File "fofa-Cscan.py", line 55, in creat_xlsx
    os.mkdir('out')
FileExistsError: [Errno 17] File exists: 'out'
报这个错误

**Comment by wudicainiao** [comment]
在windows下试试怎么样。我有if判断了out目录存不存在的。


------------------ 原始邮件 ------------------
发件人: "lgf01010"<notifications@github.com>;
发送时间: 2019年8月8日(星期四) 下午4:11
收件人: "wudicainiao/Fofa-Cscan"<Fofa-Cscan@noreply.github.com>;
抄送: "dacainiao"<820340571@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [wudicainiao/Fofa-Cscan] KeyError: 'results' (#2)





 [*]开始抓取
 Traceback (most recent call last):
 File "fofa-Cscan.py", line 73, in 
 creat_xlsx()
 File "fofa-Cscan.py", line 55, in creat_xlsx
 os.mkdir('out')
 FileExistsError: [Errno 17] File exists: 'out'
 报这个错误

**Comment by 98Kstar** [comment]
谢谢大佬回复，在win下没有试过，在centos下 下载好源码然后运行第一次时会有自动生成一个out目录，我昨天试过成功的会生成个时间格式的xlxs的文件，但是今天就报错，好几次，还会生成个out\当前时间.xlxs的不可读文件，

**Comment by wudicainiao** [comment]
你方便在win下使用吗。如果不方便我过段时间空了看一下这个问题。



------------------ 原始邮件 ------------------
发件人: "lgf01010"<notifications@github.com>;
发送时间: 2019年8月8日(星期四) 下午4:20
收件人: "wudicainiao/Fofa-Cscan"<Fofa-Cscan@noreply.github.com>;
抄送: "dacainiao"<820340571@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [wudicainiao/Fofa-Cscan] KeyError: 'results' (#2)




谢谢大佬回复，在win下没有试过，在centos下 下载好源码然后运行第一次时会有自动生成一个out目录，我昨天试过成功的会生成个时间格式的xlxs的文件，但是今天就报错，好几次，还会生成个out\当前时间.xlxs的不可读文件，

**Comment by 98Kstar** [comment]
win下正常

**Comment by H4ckForJob** [comment]
后面发现好像是要key，已经能正常开始扫描，但是扫描到一半会卡住

**Comment by wudicainiao** [comment]
我从来没卡住过可能你的网络问题？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"I Need A job!"<notifications@github.com&gt;;
发送时间:&nbsp;2019年9月5日(星期四) 中午11:32
收件人:&nbsp;"wudicainiao/Fofa-Cscan"<Fofa-Cscan@noreply.github.com&gt;;
抄送:&nbsp;"dacainiao"<820340571@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [wudicainiao/Fofa-Cscan] KeyError: 'results' (#2)




后面发现好像是要key，已经能正常开始扫描，但是扫描到一半会卡住
